const app=document.getElementById("adminApp");
let ADMIN_KEY=sessionStorage.getItem("cbt_admin_key")||"";
let currentTab="results",resultsCache=[],examsCache=[];
const $=id=>document.getElementById(id);

function adminBrand(title="模擬試験 管理画面"){
  return `<div class="brandbar admin-brandbar">
    <div class="brand-logos">
      <img src="assets/aidem-logo.png" class="brand-logo aidem" alt="AIDEM">
      <span class="brand-sep">›</span>
      <img src="assets/aidem-global-logo.png" class="brand-logo global" alt="アイデムグローバル">
      <span class="brand-sep">›</span>
      <div class="team-brand"><img src="assets/aitoku-logo.png" class="brand-logo aitoku" alt="アイトク"></div>
    </div>
    <div class="brand-title">${esc(title)}</div>
  </div>`;
}

function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function jsonp(params){return new Promise((resolve,reject)=>{const cb="cb_"+Date.now()+"_"+Math.random().toString(36).slice(2),script=document.createElement("script");const timer=setTimeout(()=>{cleanup();reject(new Error("Timeout"))},15000);function cleanup(){clearTimeout(timer);delete window[cb];script.remove()}window[cb]=d=>{cleanup();resolve(d)};script.src=CBT_CONFIG.apiUrl+"?"+new URLSearchParams({...params,callback:cb}).toString();script.onerror=()=>{cleanup();reject(new Error("Network"))};document.body.appendChild(script)})}
async function postAdmin(payload){payload.adminKey=ADMIN_KEY;await fetch(CBT_CONFIG.apiUrl,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});await new Promise(r=>setTimeout(r,1000))}
function login(){app.innerHTML=`${adminBrand("管理者ログイン")}<div class="form-card"><h2>管理者ログイン</h2><div class="field"><label>管理パスワード</label><input id="keyInput" type="password"></div><button class="btn primary full" onclick="doLogin()">ログイン</button><div class="note">パスワードはGoogle Apps ScriptのScript Propertiesで設定します。</div></div>`}
window.doLogin=async function(){const k=$("keyInput").value.trim();if(!k)return;try{const d=await jsonp({action:"adminPing",key:k});if(!d.ok)throw 0;ADMIN_KEY=k;sessionStorage.setItem("cbt_admin_key",k);dashboard()}catch{alert("パスワードが正しくありません。")}}
async function dashboard(){app.innerHTML=`${adminBrand("飲食料品製造業 模擬試験 管理画面")}<div class="admin-logout"><button class="btn secondary" onclick="logout()">ログアウト</button></div><div class="page"><div class="admin-tabs"><button id="tabResults" class="btn secondary" onclick="showTab('results')">受験結果</button><button id="tabExams" class="btn secondary" onclick="showTab('exams')">試験管理</button><button id="tabUpload" class="btn secondary" onclick="showTab('upload')">新しい試験を追加</button></div><div id="content" class="panel">読み込み中...</div></div>`;showTab(currentTab)}
window.logout=function(){sessionStorage.removeItem("cbt_admin_key");ADMIN_KEY="";login()}
window.showTab=async function(tab){currentTab=tab;["Results","Exams","Upload"].forEach(x=>{const el=$("tab"+x);if(el)el.classList.remove("active")});const cap=tab.charAt(0).toUpperCase()+tab.slice(1);if($("tab"+cap))$("tab"+cap).classList.add("active");if(tab==="results")loadResults();if(tab==="exams")loadExams();if(tab==="upload")uploadForm()}
async function loadResults(){const c=$("content");c.innerHTML="結果を読み込んでいます...";try{const d=await jsonp({action:"adminResults",key:ADMIN_KEY});if(!d.ok)throw 0;resultsCache=d.results;renderResults()}catch{c.innerHTML="読み込みに失敗しました。"}}
function renderResults(){const c=$("content");c.innerHTML=`<h2>受験結果</h2><div class="toolbar"><input id="fCompany" placeholder="企業名" oninput="filterResults()"><input id="fName" placeholder="氏名" oninput="filterResults()"><select id="fPass" onchange="filterResults()"><option value="">すべて</option><option value="true">合格</option><option value="false">不合格</option></select><button class="btn primary" onclick="exportResults()">CSV出力</button></div><div id="resultTable"></div>`;filterResults()}
window.filterResults=function(){const fc=($("fCompany")?.value||"").toLowerCase(),fn=($("fName")?.value||"").toLowerCase(),fp=$("fPass")?.value||"";const rows=resultsCache.filter(r=>(r.company||"").toLowerCase().includes(fc)&&(r.studentName||"").toLowerCase().includes(fn)&&(fp===""||String(r.passed)===fp));$("resultTable").innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>日時</th><th>企業名</th><th>氏名</th><th>試験</th><th>得点</th><th>判定</th><th>分野別</th><th>重点復習</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.timestamp)}</td><td>${esc(r.company)}</td><td>${esc(r.studentName)}</td><td>${esc(r.examTitle)}</td><td><b>${r.correct}/${r.total} (${r.percent}%)</b></td><td class="${r.passed?"good":"weak"}">${r.passed?"合格":"不合格"}</td><td class="cat-mini">${(r.categories||[]).map(c=>`${esc(c.category)}: ${c.correct}/${c.total} (${c.percent}%)`).join("<br>")}</td><td class="weak">${esc((r.weakCategories||[]).join("・")||"-")}</td></tr>`).join("")}</tbody></table></div>`}
window.exportResults=function(){const rows=[["Timestamp","Company","Student","Exam","Correct","Total","Percent","Passed","Category Scores","Weak Categories"]];resultsCache.forEach(r=>rows.push([r.timestamp,r.company,r.studentName,r.examTitle,r.correct,r.total,r.percent,r.passed,(r.categories||[]).map(c=>`${c.category}:${c.correct}/${c.total}(${c.percent}%)`).join(" | "),(r.weakCategories||[]).join(" | ")]));const csv=rows.map(a=>a.map(v=>{v=String(v??"");return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}).join(",")).join("\n");const b=new Blob(["\ufeff"+csv],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="cbt_results.csv";a.click();URL.revokeObjectURL(a.href)}
async function loadExams(){const c=$("content");c.innerHTML="試験を読み込んでいます...";try{const d=await jsonp({action:"adminExams",key:ADMIN_KEY});if(!d.ok)throw 0;examsCache=d.exams;c.innerHTML=`<h2>試験管理</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>試験名</th><th>問題数</th><th>時間</th><th>合格基準</th><th>公開</th><th>操作</th></tr></thead><tbody>${examsCache.map(e=>`<tr><td>${esc(e.id)}</td><td>${esc(e.title)}</td><td>${e.questionCount}</td><td>${e.durationMinutes}分</td><td>${e.passPercent}%</td><td>${e.published?"公開中":"非公開"}</td><td><button class="btn secondary" onclick="togglePublish('${e.id}',${!e.published})">${e.published?"非公開にする":"公開する"}</button> <button class="btn danger" onclick="deleteExam('${e.id}')">削除</button></td></tr>`).join("")}</tbody></table></div>`}catch{c.innerHTML="読み込みに失敗しました。"}}
window.togglePublish=async function(id,published){await postAdmin({action:"setPublished",id,published});loadExams()}
window.deleteExam=async function(id){if(!confirm("この試験を削除しますか？"))return;await postAdmin({action:"deleteExam",id});loadExams()}
function uploadForm(){$("content").innerHTML=`<h2>新しい試験を追加</h2><div class="field"><label>試験名</label><input id="examTitle" placeholder="例：模擬試験 第1回"></div><div class="field"><label>試験ID</label><input id="examId" placeholder="例：exam01"></div><div class="field"><label>制限時間</label><input id="duration" type="number" value="70"></div><div class="field"><label>合格基準 (%)</label><input id="passPercent" type="number" value="70"></div><div class="field"><label>CSVファイル</label><input id="csvFile" type="file" accept=".csv"></div><div class="code-help">CSV列:
No,Category,Question,A,B,C,D,Correct,Explanation

Correct は A / B / C / D
例:
1,衛生管理,手洗いについて正しいものはどれですか,選択肢A,選択肢B,選択肢C,選択肢D,B,解説</div><button class="btn primary" style="margin-top:15px" onclick="uploadExam()">アップロードして保存</button><div id="uploadMsg" class="note"></div>`}
window.uploadExam=async function(){const f=$("csvFile").files[0];if(!f){alert("CSVを選択してください。");return}const title=$("examTitle").value.trim(),id=$("examId").value.trim();if(!title||!id){alert("試験名とIDを入力してください。");return}const text=await f.text(),questions=parseCSV(text);if(!questions.length){alert("CSVを読み込めませんでした。");return}$("uploadMsg").textContent=`${questions.length}問を送信中...`;await postAdmin({action:"saveExam",exam:{id,title,subtitle:"飲食料品製造業",durationMinutes:Number($("duration").value)||70,passPercent:Number($("passPercent").value)||70,published:false,questions}});$("uploadMsg").textContent="保存しました。試験管理から公開できます。"}
function parseCSV(text){const rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch=='"'&&q&&n=='"'){cell+='"';i++}else if(ch=='"'){q=!q}else if(ch==","&&!q){row.push(cell);cell=""}else if((ch=="\n"||ch=="\r")&&!q){if(ch=="\r"&&n=="\n")i++;row.push(cell);if(row.some(x=>x.trim()!==""))rows.push(row);row=[];cell=""}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()!==""))rows.push(row);if(rows.length<2)return[];const hdr=rows[0].map(x=>x.trim().toLowerCase());const idx=n=>hdr.indexOf(n.toLowerCase());return rows.slice(1).map((r,i)=>{const corr=(r[idx("Correct")]||"A").trim().toUpperCase();return{id:Number(r[idx("No")])||i+1,category:r[idx("Category")]||"",question:r[idx("Question")]||"",choices:[r[idx("A")]||"",r[idx("B")]||"",r[idx("C")]||"",r[idx("D")]||""],correct:["A","B","C","D"].indexOf(corr),explanation:r[idx("Explanation")]||""}}).filter(q=>q.question&&q.correct>=0)}
if(!CBT_CONFIG.apiUrl){app.innerHTML=`<div class="form-card"><h2>API URL chưa được cài</h2><p>Hãy deploy Google Apps Script rồi dán URL vào config.js.</p></div>`}else if(ADMIN_KEY){dashboard()}else login();
